/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVANT_H_RPCGEN
#define _SERVANT_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define CHUNK_LENGTH 1500

typedef struct {
	u_int chunk_len;
	char *chunk_val;
} chunk;
#ifdef __cplusplus
extern "C" bool_t xdr_chunk(XDR *, chunk*);
#elif __STDC__
extern  bool_t xdr_chunk(XDR *, chunk*);
#else /* Old Style C */
bool_t xdr_chunk();
#endif /* Old Style C */


struct servant_request {
	chunk data;
};
typedef struct servant_request servant_request;
#ifdef __cplusplus
extern "C" bool_t xdr_servant_request(XDR *, servant_request*);
#elif __STDC__
extern  bool_t xdr_servant_request(XDR *, servant_request*);
#else /* Old Style C */
bool_t xdr_servant_request();
#endif /* Old Style C */


struct servant_response {
	chunk data;
};
typedef struct servant_response servant_response;
#ifdef __cplusplus
extern "C" bool_t xdr_servant_response(XDR *, servant_response*);
#elif __STDC__
extern  bool_t xdr_servant_response(XDR *, servant_response*);
#else /* Old Style C */
bool_t xdr_servant_response();
#endif /* Old Style C */


#define SERVANT ((rpc_uint)43)
#define SERVANTVERSION ((rpc_uint)1)

#ifdef __cplusplus
#define send_request ((rpc_uint)1)
extern "C" servant_response * send_request_1(servant_request *, CLIENT *);
extern "C" servant_response * send_request_1_svc(servant_request *, struct svc_req *);

#elif __STDC__
#define send_request ((rpc_uint)1)
extern  servant_response * send_request_1(servant_request *, CLIENT *);
extern  servant_response * send_request_1_svc(servant_request *, struct svc_req *);

#else /* Old Style C */
#define send_request ((rpc_uint)1)
extern  servant_response * send_request_1();
extern  servant_response * send_request_1_svc();
#endif /* Old Style C */

#endif /* !_SERVANT_H_RPCGEN */
