/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVANT_H_RPCGEN
#define _SERVANT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define CHUNK_LENGTH 1024
#define FILENAME_LENGTH 1024

typedef char *filename;

typedef struct {
	u_int chunk_len;
	char *chunk_val;
} chunk;

struct get_request {
	filename path;
	int start;
};
typedef struct get_request get_request;

struct put_request {
	filename path;
	chunk data;
	int bytes;
};
typedef struct put_request put_request;

struct _get_response {
	chunk data;
	int bytes;
};
typedef struct _get_response _get_response;

struct get_response {
	int errno;
	union {
		_get_response chunk;
	} get_response_u;
};
typedef struct get_response get_response;

#define SERVANT 43
#define SERVANTVERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define download 1
extern  get_response * download_1(get_request *, CLIENT *);
extern  get_response * download_1_svc(get_request *, struct svc_req *);
#define upload 2
extern  int * upload_1(put_request *, CLIENT *);
extern  int * upload_1_svc(put_request *, struct svc_req *);
extern int servant_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define download 1
extern  get_response * download_1();
extern  get_response * download_1_svc();
#define upload 2
extern  int * upload_1();
extern  int * upload_1_svc();
extern int servant_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_filename (XDR *, filename*);
extern  bool_t xdr_chunk (XDR *, chunk*);
extern  bool_t xdr_get_request (XDR *, get_request*);
extern  bool_t xdr_put_request (XDR *, put_request*);
extern  bool_t xdr__get_response (XDR *, _get_response*);
extern  bool_t xdr_get_response (XDR *, get_response*);

#else /* K&R C */
extern bool_t xdr_filename ();
extern bool_t xdr_chunk ();
extern bool_t xdr_get_request ();
extern bool_t xdr_put_request ();
extern bool_t xdr__get_response ();
extern bool_t xdr_get_response ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVANT_H_RPCGEN */
