/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVANT_H_RPCGEN
#define _SERVANT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define CHUNK_LENGTH 1500

typedef struct {
	u_int chunk_len;
	char *chunk_val;
} chunk;

struct servant_request {
	chunk data;
};
typedef struct servant_request servant_request;

struct servant_response {
	chunk data;
};
typedef struct servant_response servant_response;

#define SERVANT 43
#define SERVANTVERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define send_request 1
extern  servant_response * send_request_1(servant_request *, CLIENT *);
extern  servant_response * send_request_1_svc(servant_request *, struct svc_req *);
extern int servant_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define send_request 1
extern  servant_response * send_request_1();
extern  servant_response * send_request_1_svc();
extern int servant_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_chunk (XDR *, chunk*);
extern  bool_t xdr_servant_request (XDR *, servant_request*);
extern  bool_t xdr_servant_response (XDR *, servant_response*);

#else /* K&R C */
extern bool_t xdr_chunk ();
extern bool_t xdr_servant_request ();
extern bool_t xdr_servant_response ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVANT_H_RPCGEN */
