/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "servant.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

servant_response *
send_request_1(argp, clnt)
	servant_request *argp;
	CLIENT *clnt;
{
	static servant_response clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, send_request, xdr_servant_request, argp, xdr_servant_response, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
