/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "servant.h"

bool_t
xdr_chunk(xdrs, objp)
	XDR *xdrs;
	chunk *objp;
{

	if (!xdr_bytes(xdrs, (char **)&objp->chunk_val, (u_int *)&objp->chunk_len, CHUNK_LENGTH))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_servant_request(xdrs, objp)
	XDR *xdrs;
	servant_request *objp;
{

	if (!xdr_chunk(xdrs, &objp->data))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_servant_response(xdrs, objp)
	XDR *xdrs;
	servant_response *objp;
{

	if (!xdr_chunk(xdrs, &objp->data))
		return (FALSE);
	return (TRUE);
}
